apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: hananeoudaali/eureka-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: SERVER_SSL_ENABLED
              value: "true"
            - name: SERVER_SSL_KEY_STORE
              value: "/app/certs/localhost.p12"
            - name: SERVER_SSL_KEY_STORE_PASSWORD
              value: "changeit"
            - name: SERVER_SSL_KEY_STORE_TYPE
              value: "PKCS12"
          volumeMounts:
            - name: ssl-secret
              mountPath: "/app/certs"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
              scheme: HTTP
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8761
              scheme: HTTP
      volumes:
        - name: ssl-secret
          secret:
            secretName: eureka-ssl-secret
            items:
              - key: localhost.p12
                path: localhost.p12