apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-profile-config
data:
  application.yaml: |
    server:
      port: 8050
    spring:
      application:
        name: employee-profile
      datasource:
        url: jdbc:mysql://mysql-employee:3306/employee?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
    eureka:
      client:
        service-url:
          defaultZone: https://eureka-server:8761/eureka/
      instance:
        prefer-ip-address: true
    graphiql:
      enabled: true
      endpoint: /graphql
      path: /graphiql