server:
  port: 8052
  servlet:
    context-path: /graphql-api
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: secure-localhost
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
  http2:
    enabled: true
  tls:
    enabled: true
  security:
    basic:
      enabled: false

spring:
  application:
    name: graphql-api
  cloud:
    loadbalancer:
      retry:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

rate:
  limit:
    requests: 100
    duration: 1m

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    ucd.fs: DEBUG

services:
  employee-profile-url: http://localhost:8050
  absence-management-url: http://localhost:8082
  payroll-url: http://localhost:8083
  performance-review-url: http://localhost:8051

graphql:
  servlet:
    enabled: true
    cors-enabled: true