spring:
  application:
    name: employee-profile
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      name: employee-profile
  profiles:
    active: dev

server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
graphiql:
  enabled: true
  endpoint: /graphql
  path: /graphiql



jwt:
  secret: "maCleSecreteTrèsLonguePourJWTQueTuDoisChangerEtMettreEnSecurite123!"