apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - name: https
      port: 8443
      targetPort: 8443
    - name: http
      port: 80
      targetPort: 8443