server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: 1
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
  http2:
    enabled: true
  tls:
    enabled: true
  security:
    basic:
      enabled: false
spring:
  application:
    name: absence-management
  config:
    import: optional:configserver:http://localhost:8888
  security:
    user:
      name: admin
      password: secret123

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
