apiVersion: v1
kind: ConfigMap
metadata:
  name: payroll-config
data:
  application.yaml: |
    server:
      port: 8083
      ssl:
        enabled: true
        key-store: "/app/certs/localhost.p12"  # Chemin dans le conteneur
        key-store-type: PKCS12
        key-alias: "secure-localhost"
        trust-store: "/app/certs/truststore.p12"
      http2:
        enabled: true
    spring:
      datasource:
        url: jdbc:mysql://mysql-payroll-service:3306/payroll_db?useSSL=false&allowPublicKeyRetrieval=true
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
    eureka:
      client:
        service-url:
          defaultZone: https://eureka-server:8761/eureka/