apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll-service
  template:
    metadata:
      labels:
        app: payroll-service
    spec:
      containers:
        - name: payroll-service
          image: hananeoudaali/payroll-service:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: payroll-config
            - secretRef:
                name: payroll-secrets
          volumeMounts:
            - name: ssl-secrets
              mountPath: "/app/certs"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 45
      volumes:
        - name: ssl-secrets
          secret:
            secretName: payroll-secrets
            items:
              - key: ssl-key-store
                path: localhost.p12
              - key: ssl-trust-store
                path: truststore.p12