apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-payroll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-payroll
  template:
    metadata:
      labels:
        app: mysql-payroll
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payroll-secrets
                  key: db-password
            - name: MYSQL_DATABASE
              value: "payroll_db"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-payroll-pvc