server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12


eureka:
  server:
    response-cache-control: "no-cache"
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    metadata-map:
      management:
        context-path: /actuator