server:
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: secure-localhost
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
  http2:
    enabled: true
  tls:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

