spring:
  application:
    name: payroll-service
  config:
    import: optional:configserver:http://localhost:8888
    name: payroll-service
    tls:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/payroll_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: secure-localhost
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
  http2:
    enabled: true
  tls:
    enabled: true


eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    tls:
      enabled: true
      trust-store: classpath:localhost.p12
      trust-store-password: changeit
  instance:
    prefer-ip-address: true
    secure-port-enabled: true
    secure-port: 8443
    status-page-url: https://localhost:8443/actuator/info
    health-check-url: https://localhost:8443/actuator/health
    home-page-url: https://localhost:8443/

